const campaigns = [
  {s:'Atrair',n:'Desfile de Estilo 🐾 (Reels/Stories)',p:'Tutores cães/gatos porte médio-grande — maior origem real (Instagram, 136 leads)',c:'Instagram + tráfego pago',v:'Não',b:250,e:1200,r:'6.000 visitantes',x:'Grave 3 looks em cortes de 2–3 segundos, mostre nome/tamanho na tela e finalize com “Conheça a coleção”. Publique o Reels e derive 3 Stories com enquete de espécie e link rastreado.',a:'Reels vertical, sequência de Stories, capa, UTM e página de coleção.',m:'visitantes qualificados, CTR, custo por visitante e taxa visitante → lead.',i:'Usar camiseta como produto-herói enquanto o moletom M/G estiver em risco de ruptura.',t:'Teste abertura “frio chegando” versus “qual é o estilo do seu pet?”; pause o criativo com CTR abaixo do melhor após volume suficiente.'},
  {s:'Atrair',n:'SEO + Google Ads “presente personalizado pet”',p:'Tutores em busca ativa — 48 leads reais vieram do Google',c:'Google Ads + blog',v:'Não',b:150,e:750,r:'2.500 visitantes (cliques)',x:'Crie um artigo que responda intenção de presente, inclua fotos reais, faixas de preço e CTA para a coleção. Separe campanha de busca por termos de compra e negativar “grátis”, “molde” e “como fazer”.',a:'Artigo SEO, anúncio responsivo, extensões de sitelink e landing coerente com a busca.',m:'impressões, CTR, CPC, termos de pesquisa, conversão e custo por lead.',i:'A origem Google já trouxe 48 leads; preserve a mensagem de alta intenção e não mande toda busca para a home.',t:'Compare anúncio focado em presente com anúncio focado em personalização; redistribua verba para grupos com lead qualificado.'},
  {s:'Atrair',n:'Desafio de dança/UGC no TikTok',p:'Público jovem, tutores 18–30 anos — canal em crescimento (17 leads reais)',c:'TikTok',v:'Não',b:100,e:500,r:'800 visitantes',x:'Defina uma mecânica simples: vídeo do pet + transição para o look + hashtag. Publique um vídeo-farol, convide 5 microcriadores e responda aos melhores posts em até 24 horas.',a:'Vídeo-farol, roteiro de 15s, hashtag, briefing de creators e página de destino.',m:'vídeos publicados, visualizações completas, cliques, visitas e leads por creator.',i:'O objetivo é gerar prova social reutilizável; peça autorização para repostar antes de impulsionar UGC.',t:'Teste incentivo com destaque no perfil versus cupom; mantenha a alternativa que gera conteúdo e não apenas views.'},
  {s:'Atrair',n:'Retargeting no Facebook Ads',p:'Tutores 35+ que já visitaram e não converteram (15 leads reais via Facebook)',c:'Facebook Ads',v:'Não',b:60,e:300,r:'500 visitantes',x:'Crie públicos de visitantes dos últimos 30 dias, exclua compradores e mostre produto visto ou benefício de primeira compra. Limite frequência e use criativo com depoimento.',a:'Pixel/CAPI, públicos 7/30 dias, 2 anúncios e exclusões de compradores.',m:'frequência, CPM, CTR, custo por visita, leads e conversões assistidas.',i:'Retargeting precisa resolver hesitação — use prova, prazo ou ajuda; repetir o mesmo anúncio cansa a audiência.',t:'Compare prova social versus lembrete de personalização; ajuste janela e frequência semanalmente.'},
  {s:'Atrair',n:'Programa de Indicação orgânico (formalizado)',p:'Clientes e seguidores — “Indicação” já é a 2ª maior origem real (53 leads)',c:'WhatsApp + Instagram',v:'Não',b:120,e:600,r:'60 indicações geradas',x:'Crie código individual do cliente, benefício para quem indica e para o amigo, regras de uso e mensagem pronta. Dispare após entrega e exiba o convite nos Stories e no pós-compra.',a:'Regulamento curto, código/UTM por indicador, card compartilhável e planilha de conciliação.',m:'indicações, taxa de ativação, novos clientes, receita e custo do benefício.',i:'A indicação já performa na base: reduza fricção com link pronto e recompensa só após compra validada.',t:'Teste benefício fixo versus porcentagem; monitore fraude, duplicidade e margem líquida.'},
  {s:'Atrair',n:'Carteirinha Grátis: o novo mimo da marca',p:'Visitantes frios, atraídos por utilidade (não só desconto)',c:'Instagram Ads',v:'Sim',b:100,e:500,r:'45 cadastros p/ carteirinha',x:'Promova a carteirinha como utilidade para organizar vacinas. Leve a pessoa a um formulário curto, confirme consentimento e peça foto, nome, espécie e datas somente no momento adequado.',a:'Criativo utilitário, landing, formulário, página de obrigado e fluxo de emissão.',m:'cadastros, custo por carteirinha, emissão digital, ativação e compra em 30 dias.',i:'A oferta captura intenção sem depender de desconto; a venda vem depois, por educação e lembrete.',t:'Teste “organize as vacinas” versus “mimo gratuito”; mantenha a promessa mais clara e sustentável.'},
  {s:'Atrair',n:'Parceria com clínicas veterinárias (QR code)',p:'Tutores em consulta veterinária',c:'Ponto físico + QR code',v:'Sim',b:80,e:400,r:'30 cadastros via QR',x:'Selecione clínicas com público compatível, ofereça material aprovado pelo parceiro e gere um QR exclusivo por local. Treine recepção para explicar a utilidade em uma frase e acompanhar cadastros.',a:'Cartaz de balcão, cartão de bolso, QR/UTM por clínica e script da recepção.',m:'scans, cadastros por parceiro, emissão, conversão e custo por cadastro.',i:'O contexto da consulta dá credibilidade; não transforme o consultório em ponto de venda agressivo.',t:'Compare cartaz na recepção com cartão entregue após a consulta; remunere o parceiro por cadastro validado ou venda.'},
  {s:'Atrair',n:'Desafio UGC #MeuPetDeAmorDePatas',p:'Seguidores engajados',c:'Instagram (UGC)',v:'Não',b:40,e:250,r:'25 posts com hashtag',x:'Lance uma pergunta emocional, exemplo visual e prazo. Responda todos os participantes, salve os melhores em destaque e peça autorização para usar o material em anúncios e páginas.',a:'Post de lançamento, regras, destaque, formulário de autorização e banco de UGC.',m:'posts válidos, alcance, salvamentos, menções, cliques e conteúdo reutilizável.',i:'A comunidade produz ativos para as próximas campanhas; registre autor, data e permissão.',t:'Teste prompt “mostre o amor” versus “mostre o estilo”; premie participação com reconhecimento antes de desconto.'},
  {s:'Converter',n:'Landing Cupom de Boas-Vindas (10%)',p:'Visitantes vindos de Instagram/tráfego pago',c:'Landing page',v:'Não',b:150,e:600,r:'140 leads (cupom)',x:'Monte uma landing de uma única ação: headline, 3 benefícios, prova social, formulário com nome/WhatsApp/espécie e consentimento. Entregue PATAS10 na tela e por mensagem, com validade e regra visíveis.',a:'Landing mobile, cupom único, página de obrigado, evento de conversão e e-mail/WhatsApp.',m:'taxa visitante → lead, CPL, uso do cupom, receita e margem pós-desconto.',i:'O cupom só vale se o lead for acionável; não peça dados que não serão usados.',t:'Teste formulário de 3 contra 4 campos; otimize para receita por lead, não apenas volume.'},
  {s:'Converter',n:'Cadastre seu Pet, Ganhe a Carteirinha Digital',p:'Visitantes com pet, sem exigir compra',c:'Landing + WhatsApp',v:'Sim',b:150,e:600,r:'95 carteirinhas digitais emitidas',x:'Explique o benefício, capture tutor + pet + espécie + WhatsApp e dê prazo de emissão. Após o cadastro, confirme os dados, envie a carteirinha e convide para completar datas de vacina.',a:'Landing, formulário, modelo digital, automação de confirmação e FAQ.',m:'taxa de conclusão, emissão, tempo de entrega, opt-in e primeira compra.',i:'O “sem exigir compra” aumenta topo de funil; a qualidade vem da validação e do onboarding.',t:'Teste entrega instantânea versus entrega em até 24h; nunca prometa prazo que a operação não sustenta.'},
  {s:'Converter',n:'Quiz “Qual o estilo do seu pet?”',p:'Visitantes indecisos sobre produto',c:'Landing interativa',v:'Não',b:100,e:400,r:'60 leads via quiz',x:'Faça 4 perguntas (espécie, porte, ocasião e estilo), mostre resultado com 2 produtos disponíveis e CTA de compra/cadastro. Salve respostas como campos no CRM para a nutrição.',a:'Quiz mobile, lógica de recomendação, resultados por perfil e eventos por pergunta.',m:'início/conclusão, taxa por pergunta, leads, CTR do resultado e vendas.',i:'Use o quiz para reduzir escolha, não para criar entretenimento sem próximo passo.',t:'Teste resultado com 1 produto versus kit; observe ticket e conversão.'},
  {s:'Converter',n:'Anúncio Click-to-WhatsApp + chatbot',p:'Tráfego pago mobile — WhatsApp já é origem real (28 leads)',c:'WhatsApp Ads',v:'Sim',b:60,e:250,r:'40 conversas iniciadas',x:'Crie anúncio com promessa objetiva e mensagem pré-preenchida. O bot coleta nome, espécie, interesse e consentimento; oferece 3 caminhos e transfere para humano quando houver intenção de compra.',a:'Anúncio, mensagem inicial, árvore do bot, etiquetas e SLA de atendimento.',m:'conversas iniciadas, respostas do bot, transferência, tempo de resposta e vendas.',i:'A origem WhatsApp já existe; o ganho está em organizar a triagem sem perder o tom humano.',t:'Teste menu por espécie versus menu por intenção; corte perguntas que derrubam a resposta.'},
  {s:'Converter',n:'Pop-up de saída (exit-intent) com carteirinha grátis',p:'Visitantes prestes a sair sem converter',c:'Landing (pop-up)',v:'Sim',b:90,e:350,r:'35 leads recuperados',x:'Dispare uma única vez por sessão e apenas após intenção de saída ou tempo mínimo. Ofereça carteirinha, não bloqueie a navegação e entregue benefício com confirmação clara.',a:'Modal acessível, regra de frequência, formulário curto e evento de recuperação.',m:'impressões, fechamento, cadastros, taxa de recuperação e impacto na conversão.',i:'A conversão recuperada precisa ser incremental; compare com grupo sem pop-up.',t:'Teste texto de utilidade versus desconto; valide controle de frequência e experiência mobile.'},
  {s:'Converter',n:'Landings segmentadas por espécie (cão x gato)',p:'Tutores de cães (214) e gatos (81) — split real da base',c:'Landing page dupla',v:'Não',b:100,e:400,r:'80 leads (cão + gato)',x:'Crie duas versões com imagem, vocabulário e produtos adequados. Direcione pelo anúncio ou por uma escolha inicial; preserve o mesmo evento e compare conversão por espécie.',a:'Landing cão, landing gato, rotas UTM, fotos contextuais e eventos separados.',m:'conversão por espécie, CPL, CTR, produto recomendado e receita por sessão.',i:'A base tem predominância canina, mas a versão felina evita tratar gato como exceção.',t:'Teste headline emocional versus funcional em cada espécie; evite comparar sem controlar origem.'},
  {s:'Converter',n:'Formulário progressivo no passo de personalização',p:'Visitantes iniciando a personalização (foto/nome do pet)',c:'Checkout PrestaShop',v:'Sim',b:50,e:200,r:'50 personalizações concluídas',x:'Peça primeiro o dado mínimo para salvar a intenção; solicite os demais campos depois de mostrar o preview. Salve rascunho, permita retomar e explique por que a foto é necessária.',a:'Campos progressivos, autosave, preview, validação de imagem e evento de abandono.',m:'início → conclusão, abandono por campo, uploads válidos e pedidos concluídos.',i:'A foto já é um ativo estratégico da carteirinha; peça uma vez e reutilize com consentimento.',t:'Teste ordem nome → foto versus foto → nome; reduza campos com maior abandono.'},
  {s:'Converter',n:'Google Ads para landing de busca',p:'Tutores buscando “presente pet personalizado”',c:'Google Ads',v:'Não',b:50,e:200,r:'45 leads via busca paga',x:'Separe palavras de alta intenção, escreva anúncios com “personalizado” e preço/faixa quando possível e mande para landing de busca. Configure conversão de formulário e chamadas.',a:'Grupo de anúncios, lista de negativas, landing, extensões e conversões.',m:'termo, CTR, CPC, taxa de landing, CPL e lead qualificado.',i:'Não misture descoberta com intenção de compra no mesmo grupo; isso mascara o custo real.',t:'Teste correspondência e páginas por ocasião (presente, aniversário, roupa); escale só com qualidade.'},
  {s:'Relacionar',n:'Régua de nutrição (e-mail/WhatsApp)',p:'Leads e MQLs em qualificação',c:'E-mail + WhatsApp (SuiteCRM)',v:'Não',b:80,e:450,r:'60 MQL gerados',x:'Crie trilhas por espécie e interesse: D0 entrega, D2 conteúdo útil, D4 prova social, D7 recomendação e D10 convite ao atendimento. Pontue clique, resposta e visita; passe MQL quente para vendas.',a:'Segmentos, 5 mensagens, score, templates e tarefas no SuiteCRM.',m:'entrega, abertura, cliques, respostas, avanço Lead → MQL → SQL e descadastros.',i:'Nutrição deve adicionar contexto; repita o benefício certo para cada sinal de interesse.',t:'Teste assunto/gancho e intervalo entre mensagens; suprima quem comprou.'},
  {s:'Relacionar',n:'Lembrete de Vacina Amor de Patas',p:'Leads/clientes com carteirinha ativa',c:'WhatsApp automatizado',v:'Sim',b:120,e:700,r:'40 aberturas de lembrete',x:'Cadastre data, vacina, pet e consentimento. Dispare 7 dias antes, no dia e 2 dias depois; use mensagem informativa com CTA para atualizar a carteirinha ou conhecer uma recomendação.',a:'Base de datas, templates aprovados, automação, opt-out e tag de atribuição.',m:'entrega, leitura (meta planilha: 65–70%), cliques, respostas e recompras.',i:'No mês 3, 90 lembretes e 14 recompras projetadas; o ativo é recorrência, não o disparo isolado.',t:'Teste lembrete com utilidade pura versus utilidade + produto; controle janela e saturação.'},
  {s:'Relacionar',n:'Conteúdo sazonal (frio/calor, cuidados pet)',p:'Base de leads e clientes',c:'Instagram + e-mail',v:'Não',b:60,e:300,r:'20 cliques no CTA',x:'Monte calendário editorial com um problema da estação, dica prática, produto adequado e CTA. Reaproveite cada pauta em carrossel, Reels, Stories e e-mail.',a:'Pauta mensal, roteiro, criativos, e-mail e link UTM.',m:'alcance, salvamentos, cliques, resposta e venda assistida.',i:'Conteúdo útil reduz dependência de promoções e alimenta a régua de nutrição.',t:'Compare conteúdo de prevenção com look/produto; priorize salvamentos e receita assistida.'},
  {s:'Relacionar',n:'Grupo VIP “Família Amor de Patas”',p:'Clientes e leads engajados',c:'WhatsApp (comunidade)',v:'Sim',b:40,e:200,r:'35 membros ativos',x:'Defina promessa e regras antes de convidar: dicas, bastidores, acesso antecipado e atendimento. Faça onboarding individual, publique 2 conteúdos úteis por semana e limite ofertas.',a:'Nome/descrição, regras, convite, calendário e moderador responsável.',m:'membros ativos, visualizações, respostas, retenção, vendas e opt-outs.',i:'“VIP” só funciona com privilégio real; transforme o grupo em espaço de pertencimento.',t:'Teste acesso antecipado versus benefício de serviço; meça atividade, não tamanho do grupo.'},
  {s:'Relacionar',n:'Reativação de MQL “esfriado” (+30 dias sem interação)',p:'MQLs parados — base real tem 172 MQLs',c:'E-mail + WhatsApp',v:'Não',b:60,e:350,r:'25 MQL reativados',x:'Crie segmento sem abertura, clique ou resposta há 30 dias. Envie mensagem de escolha (“ainda quer receber?”), depois conteúdo relevante e, por último, oferta; retire quem não responder.',a:'Segmento de inatividade, 3 mensagens, preferência e regra de supressão.',m:'reativação, resposta, descadastro, MQL → SQL e receita recuperada.',i:'Reengajamento também limpa a base e melhora entregabilidade; não insista sem sinal.',t:'Teste pergunta de preferência versus benefício; compare qualidade dos MQLs reativados.'},
  {s:'Relacionar',n:'Webinar/Live “Cuidados no frio” com veterinário parceiro',p:'Leads e clientes interessados em bem-estar do pet',c:'Instagram Live + e-mail',v:'Não',b:40,e:250,r:'50 inscritos na live',x:'Feche pauta e responsabilidade com o veterinário, abra inscrição com pergunta de interesse e envie lembrete D-1 e H-1. Durante a live, entregue dica prática e CTA único no final.',a:'Briefing, landing de inscrição, roteiro, lembretes, moderador e replay.',m:'inscritos, presentes, retenção, perguntas, cliques e vendas pós-live.',i:'O parceiro agrega confiança; combine aprovação de claims e não faça recomendação clínica indevida.',t:'Teste live em horário alternativo e CTA de carteirinha versus produto.'},
  {s:'Relacionar',n:'Onboarding da Carteirinha (e-mail de boas-vindas)',p:'Leads que acabaram de emitir a carteirinha',c:'E-mail + WhatsApp',v:'Sim',b:30,e:150,r:'38 e-mails abertos',x:'Entregue a carteirinha, ensine como atualizar vacinas e confirme se os dados estão corretos. No segundo toque, ofereça a versão física ou um próximo passo de cuidado.',a:'E-mail de entrega, tutorial curto, confirmação de dados e tag de ativação.',m:'abertura (meta: 38), cliques, confirmação, dados completos e compra.',i:'O onboarding é o momento de provar valor; a oferta comercial entra depois da ativação.',t:'Teste e-mail com tutorial visual versus texto curto; acompanhe ativação real.'},
  {s:'Relacionar',n:'Programa de “Nível de Fidelidade” gamificado',p:'Leads e MQLs engajados',c:'WhatsApp (barra de progresso)',v:'Não',b:20,e:100,r:'30 leads que avançaram de nível',x:'Defina níveis por ações rentáveis (cadastro completo, compra, avaliação, indicação), mostre progresso e próximo marco. Evite recompensar volume sem margem.',a:'Regra de pontos, barra de progresso, mensagens e painel de saldo.',m:'avanço de nível, custo do benefício, margem, compra e retenção.',i:'Gamificação deve orientar comportamento, não virar desconto permanente.',t:'Teste pontos por compra versus pontos por dados/indicação; valide impacto na margem.'},
  {s:'Vender',n:'Liquidação Vestidos em Contagem Regressiva',p:'Base completa + retargeting',c:'Landing + Instagram Ads',v:'Não',b:150,e:1200,r:'30 vestidos vendidos (de 74)',x:'Fotografe estoque real, informe tamanhos e prazo, crie landing com contagem regressiva verdadeira e três ondas de comunicação: lançamento, prova social e último dia.',a:'Landing de oferta, inventário por tamanho, criativos, cupom e exclusões.',m:'vendas, conversão, CAC, margem, unidades por tamanho e estoque restante.',i:'Há 74 unidades paradas: a campanha deve liberar caixa sem financiar venda deficitária.',t:'Teste desconto direto versus kit; interrompa anúncio quando tamanhos críticos acabarem.'},
  {s:'Vender',n:'Kit Carteirinha + Primeira Compra',p:'Clientes de primeira compra',c:'PrestaShop (checkout)',v:'Sim',b:100,e:700,r:'60 pedidos com carteirinha física',x:'Monte SKU/kit com benefício claro, limite de elegibilidade e upsell no checkout. Confirme dados de pet, produção e envio para que o brinde não atrase o pedido.',a:'SKU kit, página, bloco no checkout, FAQ, regra de margem e etiqueta.',m:'kits vendidos, attach rate, ticket médio, margem e prazo de despacho.',i:'Conecte a primeira compra ao relacionamento; registre a carteirinha no mesmo cliente.',t:'Teste kit com preço fechado versus adicionar por valor reduzido; acompanhe ticket líquido.'},
  {s:'Vender',n:'Cross-sell automático no carrinho',p:'Clientes em checkout',c:'PrestaShop (upsell)',v:'Não',b:70,e:500,r:'45 itens extras vendidos',x:'Crie regras por produto: camiseta/moletom → bandana; vestido → acessório. Mostre 1–2 sugestões com benefício e sem tirar o cliente do carrinho.',a:'Regras de recomendação, fotos, copy, evento add-on e exclusão de itens indisponíveis.',m:'attach rate, receita incremental, ticket, margem e abandono do carrinho.',i:'A Curva ABC orienta o par: bandana disponível deve complementar os produtos A.',t:'Teste recomendação por complemento versus por preço; mantenha apenas incremento comprovado.'},
  {s:'Vender',n:'Indicação no momento da compra',p:'Clientes recém-convertidos',c:'PrestaShop + WhatsApp',v:'Não',b:60,e:400,r:'20 novos clientes indicados',x:'Após pagamento aprovado, mostre convite de uma frase e botão de compartilhar. Envie a mesma oportunidade por WhatsApp após a confirmação do pedido, com código rastreável.',a:'Página pós-compra, mensagem pronta, código por pedido e regra antifraude.',m:'compartilhamentos, cliques, novos clientes, receita e taxa de ativação.',i:'O melhor momento é após a decisão; não interrompa checkout nem condicione a entrega.',t:'Teste convite emocional versus recompensa; atrele a recompensa à compra validada.'},
  {s:'Vender',n:'Recuperação de carrinho abandonado (3 mensagens)',p:'Clientes que iniciaram checkout e não finalizaram',c:'E-mail + WhatsApp automatizado',v:'Não',b:90,e:550,r:'25 carrinhos recuperados',x:'Dispare D+1h lembrete do produto, D+24h prova/ajuda e D+48h incentivo limitado. Exclua pedidos pagos, respeite consentimento e encaminhe dúvidas para atendimento.',a:'Eventos de carrinho, 3 templates, deep link, regra de exclusão e dashboard.',m:'recuperação, receita, desconto concedido, tempo até compra e opt-out.',i:'A primeira mensagem remove esquecimento; reserve incentivo para a última e proteja margem.',t:'Teste frete/ajuda versus desconto; compare receita líquida por carrinho.'},
  {s:'Vender',n:'Frete grátis condicional (compre 2, leve 3 bandanas)',p:'Clientes com ticket abaixo da média (R$ 82,71)',c:'PrestaShop (regra de frete)',v:'Não',b:70,e:400,r:'35 pedidos com 3 unidades',x:'Configure regra sem conflito com outros cupons, comunique o limiar no produto e no carrinho e simule margem com frete por região antes de publicar.',a:'Regra de carrinho, faixa de frete, banner, contador e teste de margem.',m:'pedidos elegíveis, ticket, unidades/pedido, custo de frete e margem.',i:'Use R$ 82,71 como referência; o objetivo é elevar unidades sem corroer contribuição.',t:'Teste “frete grátis” versus “3 por preço especial”; mantenha o que gera margem maior.'},
  {s:'Vender',n:'“Compre e Doe” — parte da venda para ONG de proteção animal',p:'Clientes sensíveis à causa animal',c:'Checkout PrestaShop + Instagram',v:'Não',b:30,e:150,r:'40 pedidos com doação ativada',x:'Formalize ONG, percentual/valor, período e prestação de contas. Publique a mecânica antes da venda, exiba no checkout e reporte resultado com comprovantes.',a:'Termo/parceria, página da causa, selo no checkout, posts e relatório pós-campanha.',m:'pedidos ativados, conversão, ticket, margem, valor doado e alcance.',i:'Transparência é parte da oferta; não use causa como urgência sem comprovação.',t:'Teste valor fixo versus percentual e acompanhe confiança, conversão e margem.'},
  {s:'Vender',n:'Live Shopping no Instagram (personalização ao vivo)',p:'Seguidores engajados, interessados em ver o processo',c:'Instagram Live + link de compra',v:'Não',b:30,e:100,r:'15 vendas na live',x:'Escolha 3 produtos disponíveis, ensaie personalização, fixe link e código da live. Mostre bastidores, responda objeções e faça chamadas de compra em blocos, sem prometer estoque ilimitado.',a:'Roteiro, cenário, links, código exclusivo, moderador e FAQ de entrega.',m:'pico de audiência, retenção, cliques, vendas atribuídas e ticket.',i:'Ver o processo reduz risco percebido do personalizado; deixe o produto pronto para compra.',t:'Teste demonstração de produto versus tutorial; use replay com janela de atribuição definida.'},
  {s:'Fidelizar',n:'Clube “Família Amor de Patas” (pontos)',p:'Clientes ativos',c:'SuiteCRM + e-mail',v:'Não',b:70,e:500,r:'80 clientes cadastrados no clube',x:'Defina benefícios sustentáveis, níveis, pontos por compra/avaliação/indicação e expiração clara. Convide 7 dias após a entrega e mostre o saldo em cada contato.',a:'Regulamento, cadastro, saldo, e-mail de convite, calendário e suporte.',m:'adesão, ativos 30/60/90 dias, resgate, recompra, margem e churn.',i:'O clube deve aumentar frequência e dados próprios; benefício sem uso não cria fidelidade.',t:'Teste benefício de serviço/experiência versus desconto; compare recompra e margem.'},
  {s:'Fidelizar',n:'Carteirinha como motor de recompra',p:'Clientes com carteirinha ativa',c:'WhatsApp (lembretes)',v:'Sim',b:60,e:400,r:'35 recompras atribuídas',x:'Use datas registradas para criar régua de vacina, aniversário e atualização. Inclua recomendação contextual de produto, link profundo e código exclusivo para atribuir a recompra.',a:'Base de eventos, templates, automação, código e fila de exceções.',m:'recompras, receita atribuída, taxa de abertura, clique, margem e opt-out.',i:'O ativo já entregue vira calendário de valor; não trate todo lembrete como disparo promocional.',t:'Teste janela de 7 versus 14 dias e CTA de atualização versus coleção.'},
  {s:'Fidelizar',n:'Indicação dupla (cliente + amigo)',p:'Clientes fidelizados',c:'WhatsApp + Instagram',v:'Sim',b:30,e:200,r:'15 pares indicador/indicado',x:'Convide clientes com 2+ compras para compartilhar um código de benefício duplo. Valide cada par, aplique benefício após a primeira compra do amigo e registre o vínculo no CRM.',a:'Código individual, card compartilhável, regras, validação e mensagem pós-compra.',m:'pares válidos, ativação, CAC indicado, receita e margem após incentivos.',i:'A dupla recompensa torna o pedido social sem penalizar o cliente existente.',t:'Teste benefício igual versus maior para o amigo; limite por período e cliente.'},
  {s:'Fidelizar',n:'Pesquisa de satisfação (NPS) gamificada',p:'Clientes pós-entrega',c:'E-mail/WhatsApp',v:'Não',b:20,e:100,r:'70 respostas de pesquisa',x:'Envie após confirmação de entrega, faça a pergunta NPS e uma pergunta aberta. Agradeça, convide detratores para atendimento e peça depoimento aos promotores; só depois ofereça incentivo permitido.',a:'Pesquisa curta, segmentação por nota, alertas, script de recuperação e painel.',m:'respostas, NPS, taxa por faixa, tempo de resolução e depoimentos autorizados.',i:'NPS sem fechamento de ciclo vira vaidade; cada detrator precisa de dono e prazo.',t:'Teste envio D+2 versus D+7 e compare resposta sem contaminar a nota.'},
  {s:'Fidelizar',n:'Aniversário do pet (desconto automático)',p:'Clientes com data de nascimento do pet cadastrada (carteirinha)',c:'E-mail + WhatsApp automatizado',v:'Sim',b:50,e:350,r:'20 recompras geradas',x:'Capture a data com consentimento, dispare 14 dias antes e no aniversário, com desconto de validade curta e produtos disponíveis. Evite enviar para pedidos recentes ou clientes em atendimento.',a:'Campo de data, automação, cupom individual, catálogo e exclusões.',m:'entrega, cliques, uso do cupom, recompra, ticket e margem.',i:'A data torna a mensagem pessoal; mantenha a celebração como protagonista, não apenas o desconto.',t:'Teste 7 versus 14 dias de antecedência e benefício percentual versus brinde.'},
  {s:'Fidelizar',n:'Reativação de clientes inativos (+90 dias sem compra)',p:'Clientes que compraram uma vez e sumiram',c:'E-mail + WhatsApp',v:'Não',b:40,e:300,r:'18 clientes reativados',x:'Separe clientes por última categoria, exclua reclamações abertas e faça 3 contatos: lembrar vínculo, recomendar novidade e oferecer retorno com prazo. Marque reativados e pare após compra.',a:'Segmento RFM simples, 3 mensagens, recomendação por compra e cupom.',m:'reativação, receita incremental, margem, desconto e descadastro.',i:'A categoria anterior dá relevância; não trate o cliente inativo como lead frio.',t:'Teste recomendação da mesma categoria versus complementar; compare margem e recorrência.'},
  {s:'Fidelizar',n:'Conteúdo exclusivo de bastidores para fidelizados',p:'Clientes fidelizados (clube)',c:'Instagram fechado/WhatsApp',v:'Não',b:20,e:100,r:'50 engajamentos',x:'Publique bastidores reais de produção, votação de estampas e acesso antecipado. Mantenha frequência previsível e moderador; reserve a comunidade para quem tem relação ativa.',a:'Calendário, fotos/vídeos de bastidores, enquetes e canal fechado.',m:'visualizações, respostas, votos, retenção e vendas de lançamentos.',i:'Acesso e participação são benefícios de baixo custo e alta percepção de proximidade.',t:'Teste bastidor de produto versus história da equipe; use resposta e retenção como critério.'},
  {s:'Fidelizar',n:'Selo digital “Cliente Fidelizado” compartilhável',p:'Clientes fidelizados que compraram 2+ vezes',c:'Instagram (compartilhamento)',v:'Não',b:10,e:50,r:'25 compartilhamentos',x:'Crie selo bonito, personalizado com nome do pet e instrução simples de compartilhamento. Entregue após a segunda compra ou NPS positivo, com autorização de uso da imagem.',a:'Arte do selo, template personalizado, mensagem de entrega e hashtag.',m:'selos emitidos, compartilhamentos, alcance, menções e indicações.',i:'O selo transforma satisfação em prova social; não o entregue antes de a experiência merecer.',t:'Teste selo estático versus story animado e rastreie menções/visitas.'}
];

const funnel = [
  {name:'Atrair',journey:'Visitante',base:'18.450',goal:'23.063',rate:'+25%',color:'amber'},
  {name:'Converter',journey:'Lead',base:'2.768',goal:'4.151',rate:'15% → 18%',color:'coral'},
  {name:'Relacionar',journey:'MQL / SQL',base:'1.300 / 700',goal:'2.076 / 1.204',rate:'50% / 58%',color:'plum'},
  {name:'Vender',journey:'Cliente',base:'516',goal:'939',rate:'73,7% → 78%',color:'mint'},
  {name:'Fidelizar',journey:'Fidelizado / Promotor',base:'124 / 45',goal:'263 / 105',rate:'28% / 40%',color:'gold'}
];
const calendar = [
 ['Semana 1','Atrair','Desfile de Estilo 🐾 (lançamento)','Marketing'],['Semana 1','Atrair','SEO + Google Ads','Marketing'],['Semana 1','Atrair','Carteirinha Grátis (teaser)','Marketing'],['Semana 2','Atrair','Programa de Indicação orgânico (formalização)','Vendas/CRM'],['Semana 2','Atrair','Parceria com clínicas veterinárias','Vendas/Parcerias'],['Semana 2','Converter','Landing Cupom de Boas-Vindas','Marketing'],['Semana 3','Converter','Cadastre seu Pet, Ganhe a Carteirinha Digital','Marketing/CRM'],['Semana 3','Converter','Landings segmentadas por espécie','Marketing'],['Semana 3','Atrair','Desafio TikTok','Marketing'],['Semana 4','Atrair','Retargeting Facebook Ads','Marketing'],['Semana 4','Atrair','Desafio UGC #MeuPetDeAmorDePatas','Marketing'],['Semana 4','Converter','Quiz “Qual o estilo do seu pet?”','Marketing'],['Semana 5','Converter','Anúncio Click-to-WhatsApp + chatbot','Marketing/Atendimento'],['Semana 5','Converter','Pop-up de saída (exit-intent)','Marketing'],['Semana 5','Relacionar','Régua de nutrição (e-mail/WhatsApp)','CRM/Vendas'],['Semana 6','Converter','Formulário progressivo no checkout','E-commerce'],['Semana 6','Converter','Google Ads para landing de busca','Marketing'],['Semana 6','Relacionar','Lembrete de Vacina Amor de Patas (piloto)','CRM/Vendas'],['Semana 7','Relacionar','Onboarding da Carteirinha','CRM'],['Semana 7','Relacionar','Grupo VIP Família Amor de Patas','Atendimento'],['Semana 7','Relacionar','Conteúdo sazonal','Marketing'],['Semana 8','Relacionar','Reativação de MQL esfriado','CRM/Vendas'],['Semana 8','Relacionar','Webinar/Live com veterinário parceiro','Marketing/Parcerias'],['Semana 8','Relacionar','Programa de Nível de Fidelidade','CRM'],['Semana 9','Vender','Liquidação Vestidos em Contagem Regressiva','Marketing/Vendas'],['Semana 9','Vender','Kit Carteirinha + Primeira Compra','Vendas'],['Semana 9','Vender','Recuperação de carrinho abandonado','E-commerce'],['Semana 10','Vender','Cross-sell automático no carrinho','E-commerce'],['Semana 10','Vender','Frete grátis condicional (2 leve 3)','E-commerce'],['Semana 10','Vender','Indicação no momento da compra','Vendas'],['Semana 11','Vender','“Compre e Doe” (causa animal)','Marketing/Vendas'],['Semana 11','Vender','Live Shopping no Instagram','Marketing'],['Semana 11','Fidelizar','Clube Família Amor de Patas (lançamento)','CRM/Vendas'],['Semana 12','Fidelizar','Carteirinha como motor de recompra (réguas)','CRM/Vendas'],['Semana 12','Fidelizar','Aniversário do pet (automação)','CRM'],['Semana 12','Fidelizar','Reativação de clientes inativos','CRM/Vendas'],['Semana 12','Fidelizar','Indicação dupla + NPS gamificado','Atendimento'],['Contínuo','Fidelizar','Conteúdo exclusivo de bastidores','Marketing'],['Contínuo','Fidelizar','Selo digital “Cliente Fidelizado”','Marketing']
];
const stageClass = s => `stage-${s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}`;
const money = n => n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const esc = value => String(value).replace(/[&<>'"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));

function renderKPIs(){
  const cards=[['Visitantes alvo','23.063','+25% sobre baseline'],['Leads alvo','4.151','taxa alvo de 18%'],['Clientes alvo','939','taxa SQL → cliente de 78%'],['Recompra real','24%','base para a fidelização']];
  document.querySelector('#kpiGrid').innerHTML=cards.map(([l,v,d])=>`<div class="col-sm-6 col-xl-3"><div class="kpi-card"><span class="kpi-label">${l}</span><strong>${v}</strong><small class="kpi-delta">${d}</small></div></div>`).join('');
}
function renderFunnel(){document.querySelector('#funnelRoadmap').innerHTML=funnel.map(f=>`<div class="funnel-step"><span class="eyebrow">${f.name}</span><b>${f.journey}</b><small>${f.base} → <span class="goal">${f.goal}</span></small><small>${f.rate}</small></div>`).join('')}
function renderBudget(){
  const mode=document.querySelector('#budgetScenario').value, key=mode==='enxuto'?'b':'e', totals={}; campaigns.forEach(c=>totals[c.s]=(totals[c.s]||0)+c[key]); const max=Math.max(...Object.values(totals)); const total=Object.values(totals).reduce((a,b)=>a+b,0);
  document.querySelector('#budgetSummary').innerHTML=Object.entries(totals).map(([s,v])=>`<div class="budget-row"><label>${s}</label><span class="budget-bar"><i style="width:${Math.round(v/max*100)}%"></i></span><strong>${money(v)}</strong></div>`).join(''); document.querySelector('#budgetTotal').textContent=money(total)+(mode==='enxuto'?' / mês':' / 90 dias');
}
function renderFilters(){document.querySelector('#stageFilters').innerHTML=['Todas',...funnel.map(f=>f.name)].map(s=>`<button class="filter-btn ${s==='Todas'?'active':''}" data-stage="${s}">${s}</button>`).join(''); document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCampaigns()}))}
function renderCampaigns(){
  const query=document.querySelector('#campaignSearch').value.trim().toLowerCase(), stage=document.querySelector('.filter-btn.active')?.dataset.stage||'Todas', onlyCard=document.querySelector('#cardFilter').checked;
  const filtered=campaigns.map((c,i)=>({...c,i})).filter(c=>(stage==='Todas'||c.s===stage)&&(!onlyCard||c.v==='Sim')&&(!query||Object.values(c).join(' ').toLowerCase().includes(query)));
  document.querySelector('#campaignGrid').innerHTML=filtered.map(c=>`<div class="col-md-6 col-xl-4"><article class="campaign-card"><div class="campaign-top"><span class="stage-tag ${stageClass(c.s)}">${c.s}</span><span class="card-number">#${String(c.i+1).padStart(2,'0')}</span></div><h3>${esc(c.n)}</h3><p>${esc(c.p)}</p><div class="card-meta"><span class="meta-pill">◉ ${esc(c.c)}</span>${c.v==='Sim'?'<span class="meta-pill cardinal">✦ Carteirinha</span>':''}</div><div class="card-footer-line"><small>${money(c.b)}/mês · meta ${esc(c.r)}</small><a href="#" class="open-recipe" data-index="${c.i}">Abrir receita →</a></div></article></div>`).join('');
  document.querySelector('#campaignCount').textContent=`${filtered.length} de ${campaigns.length} campanhas`; document.querySelector('#emptyState').classList.toggle('d-none',filtered.length>0); document.querySelectorAll('.open-recipe').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openRecipe(Number(a.dataset.index))}));
}
const practicalCopy = [
  'Reels com 3 looks, enquete de espécie e CTA para conhecer a coleção.',
  'Anúncio de busca: “Presente personalizado para pet” + artigo/landing de apoio.',
  'Vídeo de 15 segundos com transição do pet para o look e hashtag do desafio.',
  'Anúncio de retorno com prova social para quem visitou e não concluiu o cadastro.',
  'Card compartilhável com código individual e benefício para tutor e amigo.',
  'Landing de utilidade: cadastro do pet → emissão da carteirinha digital.',
  'Cartaz de clínica com QR code individual e instrução de uma frase.',
  'Post participativo com pergunta emocional, prazo e autorização de repost.',
  'Landing de captura com cupom PATAS10 entregue na tela e no WhatsApp.',
  'Formulário curto para emitir carteirinha e confirmar dados do pet.',
  'Quiz de 4 perguntas com recomendação de produto ao final.',
  'Fluxo de chatbot: espécie → interesse → consentimento → atendimento humano.',
  'Pop-up de saída com benefício útil e frequência limitada por sessão.',
  'Duas versões de landing: uma para cães e outra para gatos.',
  'Checkout com campos progressivos, autosave e retomada da personalização.',
  'Anúncio de alta intenção com extensão de sitelinks e conversão de formulário.',
  'Régua de 5 contatos com conteúdo, prova social, score e tarefa de vendas.',
  'WhatsApp: aviso de vacina, CTA de atualização e tag de recompra.',
  'Carrossel sazonal com problema, dica prática, produto e CTA rastreado.',
  'Convite para comunidade com regras, benefício real e calendário de conteúdo.',
  'Sequência de reativação com pergunta de preferência e regra de supressão.',
  'Página de inscrição para live com lembretes D-1 e H-1 e CTA final.',
  'E-mail de entrega da carteirinha com tutorial e próximo passo de ativação.',
  'Barra de progresso no WhatsApp mostrando pontos e próximo nível.',
  'Landing de liquidação com estoque por tamanho, prazo real e contagem regressiva.',
  'Bloco de kit no checkout com benefício, margem e confirmação de dados.',
  'Recomendação automática de bandana relacionada ao item no carrinho.',
  'Tela pós-compra com botão de compartilhamento e código rastreável.',
  'Sequência de carrinho: lembrete, ajuda/prova e incentivo final limitado.',
  'Barra de progresso do carrinho até 3 bandanas para liberar frete.',
  'Checkout com selo da causa, regra de doação e link para prestação de contas.',
  'Live com demonstração, código exclusivo, perguntas e link fixado.',
  'E-mail de convite ao clube com saldo inicial e benefícios sustentáveis.',
  'WhatsApp acionado por data de vacina com recomendação contextual.',
  'Card de indicação dupla com código do cliente e validação do amigo.',
  'Pesquisa NPS pós-entrega com roteamento por nota e pedido de depoimento.',
  'Mensagem de aniversário com cupom individual e catálogo elegível.',
  'Régua de retorno baseada na última categoria comprada e margem.',
  'Conteúdo fechado com bastidores, votação de estampas e acesso antecipado.',
  'Selo digital personalizado, instrução de compartilhamento e hashtag.'
];
function mockupKind(c){
  const n=c.n.toLowerCase();
  if(n.includes('live')||n.includes('webinar')) return 'event';
  if(n.includes('quiz')) return 'quiz';
  if(n.includes('landing')||n.includes('cadastre')||n.includes('pop-up')||n.includes('formulário')) return 'landing';
  if(n.includes('google')||n.includes('seo')) return 'search';
  if(n.includes('checkout')||n.includes('carrinho')||n.includes('cross-sell')||n.includes('frete')||n.includes('kit')||n.includes('compre e doe')) return 'checkout';
  if(n.includes('e-mail')||n.includes('régua')||n.includes('onboarding')||n.includes('nps')) return 'email';
  if(n.includes('whatsapp')||n.includes('carteirinha como')||n.includes('aniversário')||n.includes('reativação')) return 'whatsapp';
  if(n.includes('indicação')) return 'referral';
  if(n.includes('clube')||n.includes('nível')) return 'loyalty';
  return 'social';
}
function renderMockup(c,index){
  const kind=mockupKind(c), copy=practicalCopy[index], image=kind==='social'?'assets/hero-pet-studio-v2.png':kind==='event'?'assets/content-production-v2.png':'assets/product-flatlay-v2.png';
  const head=`<div class="applied-mockup-head"><span>MOCKUP ${String(index+1).padStart(2,'0')} · ${kind.toUpperCase()}</span><small>Exemplo de aplicação</small></div>`;
  const foot=`<div class="mockup-proof"><span>✓ Peça adaptável</span><span>◉ CTA: ${esc(c.r)}</span><span>↗ Canal: ${esc(c.c)}</span></div>`;
  let body='';
  if(kind==='social') body=`<div class="social-mock"><div class="social-top"><b>amordepatas.oficial</b><small>Patrocinado · ${esc(c.s)}</small></div><div class="social-art"><img src="${image}" alt="Visual aplicado da campanha ${esc(c.n)}"><div class="social-overlay"><span>${esc(c.s.toUpperCase())}</span><strong>${esc(c.n.replace(/\s*\([^)]*\)/,'').slice(0,50))}</strong><em>Seu pet, seu estilo, seu momento.</em></div></div><div class="social-caption"><b>amordepatas.oficial</b> ${esc(copy)} <strong>Saiba mais →</strong></div></div>`;
  if(kind==='search') body=`<div class="search-mock"><div class="search-line"><span>⌕</span><span>presente personalizado pet</span><b>×</b></div><small class="search-result-label">Anúncio · busca paga</small><div class="search-result"><div><span class="ad-tag">Patrocinado</span> <b>amordepatas.com.br</b></div><h4>Presente personalizado para pet | Amor de Patas</h4><p>Crie uma peça única com o nome e a foto do seu companheiro. Veja modelos e personalize online.</p><a>Conhecer coleção ›</a></div><div class="search-note">Hipótese: intenção de busca alta → landing específica → captura qualificada.</div></div>`;
  if(kind==='landing') body=`<div class="landing-wire"><div class="wire-hero"><div><span class="mock-label">AMOR DE PATAS · ${esc(c.s.toUpperCase())}</span><h4>${esc(c.n.replace(/\s*\([^)]*\)/,'').slice(0,52))}</h4><p>${esc(copy)}</p><button class="wire-btn">Começar agora →</button></div><img src="${image}" alt="Produto da campanha ${esc(c.n)}"></div><div class="wire-form"><strong>Próximo passo do visitante</strong><div class="wire-fields"><span>Nome do tutor</span><span>WhatsApp</span><span>Espécie ▾</span></div><button class="wire-btn secondary">Continuar cadastro</button></div></div>`;
  if(kind==='quiz') body=`<div class="quiz-mock"><div class="quiz-progress"><span style="width:60%"></span></div><small>PERGUNTA 3 DE 4</small><h4>Qual é o estilo que mais combina com ${esc(c.s==='Atrair'?'seu pet':'a sua família')}?</h4><div class="quiz-options"><button>Clássico e confortável</button><button>Divertido e colorido</button><button>Minimalista e elegante</button></div><p>Ao final: recomendação + captura de WhatsApp + CTA de produto.</p></div>`;
  if(kind==='whatsapp') body=`<div class="chat-mock"><div class="chat-head"><span>AP</span><div><b>Amor de Patas</b><small>online agora</small></div></div><div class="chat-body"><div class="chat-date">HOJE</div><div class="bubble received">Oi, ${esc(c.s==='Fidelizar'?'família Amor de Patas':'tutor')}! 🐾 ${esc(copy)}</div><div class="bubble sent">Quero saber mais. Como faço?</div><div class="bubble received">Perfeito. Posso te enviar o próximo passo e registrar a preferência do seu pet?</div><div class="chat-cta">[ CTA rastreado ] ${esc(c.r)}</div></div></div>`;
  if(kind==='email') body=`<div class="email-mock"><div class="email-bar"><span>De: relacionamento@amordepatas.com.br</span><span>Assunto: ${esc(c.n.replace(/\s*\([^)]*\)/,'').slice(0,58))}</span></div><div class="email-letter"><span class="mock-label">AMOR DE PATAS</span><h4>${esc(copy)}</h4><p>Olá, família! Preparamos este próximo passo para manter o cuidado com seu pet presente na rotina.</p><button class="wire-btn">Acessar benefício →</button><small>Preferências e descadastro no rodapé.</small></div></div>`;
  if(kind==='checkout') body=`<div class="checkout-mock"><div class="checkout-products"><div class="checkout-item"><span class="thumb">🐾</span><div><b>Produto personalizado</b><small>Nome do pet · tamanho selecionado</small></div><strong>R$ 74,90</strong></div><div class="checkout-offer"><span>OFERTA CONTEXTUAL</span><b>${esc(copy)}</b><button class="wire-btn">Adicionar ao pedido</button></div></div><div class="checkout-summary"><b>Resumo do pedido</b><div><span>Subtotal</span><span>R$ 74,90</span></div><div><span>Benefício da campanha</span><span class="positive">aplicado ✓</span></div><hr><div><strong>Total</strong><strong>R$ 74,90</strong></div><button class="wire-btn secondary">Finalizar compra</button></div></div>`;
  if(kind==='event') body=`<div class="event-mock"><div class="event-visual"><img src="${image}" alt="Bastidores da ação ${esc(c.n)}"><span>AO VIVO · 20:00</span></div><div class="event-info"><span class="mock-label">EVENTO DE RELACIONAMENTO</span><h4>${esc(c.n)}</h4><p>${esc(copy)}</p><div class="event-fields"><span>Seu nome</span><span>Seu WhatsApp</span></div><button class="wire-btn">Reservar minha vaga →</button></div></div>`;
  if(kind==='referral') body=`<div class="referral-mock"><div class="referral-card"><span class="referral-icon">↗</span><span class="mock-label">CONVITE PERSONALIZADO</span><h4>Compartilhe o cuidado.</h4><p>${esc(copy)}</p><div class="referral-code">AMIGO-AP-2026 <button>Copiar</button></div><button class="wire-btn">Compartilhar no WhatsApp</button></div><div class="referral-result"><b>Rastreabilidade</b><span>Indicador: cliente AP-0001</span><span>Indicado: aguardando cadastro</span><span>Status: benefício pendente de compra</span></div></div>`;
  if(kind==='loyalty') body=`<div class="loyalty-mock"><div class="loyalty-head"><span>FAMÍLIA AMOR DE PATAS</span><b>NÍVEL 02</b></div><h4>${esc(c.n)}</h4><p>${esc(copy)}</p><div class="loyalty-progress"><span style="width:68%"></span></div><div class="loyalty-foot"><span>680 pontos</span><b>Próximo nível: 1.000</b></div><button class="wire-btn">Ver benefícios disponíveis →</button></div>`;
  return head+body+foot;
}
function openRecipe(index){
  const c=campaigns[index]; document.querySelector('#modalEyebrow').textContent=`${c.s} · campanha ${String(index+1).padStart(2,'0')}`; document.querySelector('#modalTitle').textContent=c.n;
  document.querySelector('#modalMeta').innerHTML=`<span class="meta-pill">Público: ${esc(c.p)}</span><span class="meta-pill">Canal: ${esc(c.c)}</span><span class="meta-pill">Carteirinha: ${c.v}</span><span class="meta-pill">Enxuto: ${money(c.b)}/mês</span><span class="meta-pill">Escala: ${money(c.e)}/90 dias</span><span class="meta-pill">Resultado: ${esc(c.r)}</span>`;
  const common={Atrair:['Defina objetivo, público e rastreio','Produza e revise os ativos','Publique, distribua e responda','Leia sinais de qualidade','Otimize e documente'],Converter:['Defina a promessa e o evento de conversão','Monte a experiência sem fricção','Ative a captura e entregue o benefício','Roteie o lead para a próxima etapa','Otimize a taxa e a qualidade'],Relacionar:['Monte segmento, consentimento e score','Prepare a régua e o conteúdo útil','Dispare no ritmo e faça atendimento','Passe sinais quentes para vendas','Reative ou suprima conforme resposta'],Vender:['Valide oferta, preço, margem e estoque','Configure página, checkout e rastreio','Ative a comunicação e o atendimento','Confirme pedido e atribuição','Realocar verba pela receita líquida'],Fidelizar:['Defina benefício, elegibilidade e regra','Prepare automação e experiência','Convide no momento certo','Feche o ciclo com pedido de feedback','Transforme satisfação em recompra/indicação']}[c.s];
  const texts=[`Comece com uma ficha de campanha: objetivo = ${esc(c.r)}, público = ${esc(c.p)} e responsável no calendário. Registre origem, consentimento e uma UTM única antes de produzir qualquer peça.`,`${esc(c.x)}`,`Ative em ${esc(c.c)}. ${esc(c.a)} Garanta que o link funcione no celular, que o estoque esteja atualizado e que o atendimento conheça o script da campanha.`,`Monitore diariamente a entrega e, em até 15 minutos, encaminhe respostas ou leads com intenção de compra ao responsável. Registre no SuiteCRM a etapa, interesse, espécie, origem, resultado e próxima tarefa.`,`Meça ${esc(c.m)} ${esc(c.i)} Separe resultado direto de assistido e faça o fechamento somente após conferir vendas, margem e qualidade do lead.`,`Aprendizado e próximo teste: ${esc(c.t)} Ao final do ciclo, mantenha, ajuste ou pause com base em custo por resultado e contribuição para a etapa seguinte.`];
  document.querySelector('#modalSteps').innerHTML=texts.map((t,i)=>`<div class="recipe-step"><span class="step-no">${i+1}</span><div><h4>${common[Math.min(i,common.length-1)]}</h4><p>${t}</p></div></div>`).join('');
  document.querySelector('#modalSidebar').innerHTML=`<div class="side-card"><h4>Resultado planejado</h4><p><strong>${esc(c.r)}</strong><br>Investimento enxuto: ${money(c.b)}/mês<br>Investimento escala: ${money(c.e)}/90 dias</p></div><div class="side-card"><h4>Ativo obrigatório</h4><p>${esc(c.a)}</p></div><div class="side-card"><h4>Insight de execução</h4><p>${esc(c.i)}</p></div><div class="side-card"><h4>Critério de parada</h4><p>Não escalar se houver ruptura de estoque, tracking quebrado, opt-out alto ou queda persistente de qualidade. Corrija a causa e registre a decisão.</p></div>`;
  document.querySelector('#modalMockup').innerHTML=renderMockup(c,index);
  bootstrap.Modal.getOrCreateInstance(document.querySelector('#campaignModal')).show();
}
function renderCalendar(){document.querySelector('#calendarBody').innerHTML=calendar.map((r,i)=>`<tr><td><strong>${r[0]}</strong></td><td><span class="calendar-stage ${stageClass(r[1])}">${r[1]}</span></td><td>${esc(r[2])}</td><td class="text-muted">${esc(r[3])}</td><td><select class="status-select calendar-status" data-row="${i}"><option>Planejado</option><option>Em produção</option><option>Ativo</option><option>Concluído</option><option>Bloqueado</option></select></td></tr>`).join(''); document.querySelectorAll('.calendar-status').forEach(s=>{const key=`calendar-${s.dataset.row}`;s.value=localStorage.getItem(key)||'Planejado';s.addEventListener('change',()=>localStorage.setItem(key,s.value))})}
function renderChecklist(){const items=['UTMs e eventos de conversão testados','Consentimentos e opt-out configurados','Estoque e margem validados por campanha','Landing e checkout revisados no celular','Scripts de atendimento e SLA definidos','SuiteCRM com campos, tags e responsáveis','Calendário editorial e criativos aprovados','Painel semanal com custo e receita','Parceiros/ONGs com regras aprovadas','Critérios de pausa e aprendizado combinados']; document.querySelector('#launchChecklist').innerHTML=items.map((x,i)=>`<label class="check-item"><input type="checkbox" data-check="${i}"><span>${x}</span></label>`).join(''); document.querySelectorAll('[data-check]').forEach(input=>{const key=`check-${input.dataset.check}`;input.checked=localStorage.getItem(key)==='1';input.parentElement.classList.toggle('done',input.checked);input.addEventListener('change',()=>{localStorage.setItem(key,input.checked?'1':'0');input.parentElement.classList.toggle('done',input.checked)})})}
function copyCalendar(){const text=calendar.map(r=>r.join(' | ')).join('\n'); navigator.clipboard?.writeText(text).then(()=>{const b=document.querySelector('#copyCalendarBtn'),old=b.textContent;b.textContent='Copiado ✓';setTimeout(()=>b.textContent=old,1600)}).catch(()=>alert(text))}
document.addEventListener('DOMContentLoaded',()=>{renderKPIs();renderFunnel();renderFilters();renderCampaigns();renderBudget();renderCalendar();renderChecklist();document.querySelector('#campaignSearch').addEventListener('input',renderCampaigns);document.querySelector('#cardFilter').addEventListener('change',renderCampaigns);document.querySelector('#budgetScenario').addEventListener('change',renderBudget);document.querySelector('#copyCalendarBtn').addEventListener('click',copyCalendar);document.querySelector('#printBtn').addEventListener('click',()=>window.print())});
